version: '2'
services:
  mysql:
    restart: always
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker_build/mysql/conf:/etc/mysql/conf.d
      - ./docker_build/mysql/data:/var/lib/mysql
      - ./docker_build/mysql/init.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: app

  web:
    # restart: always
    build: "."
    expose:
      - "3000"
    volumes:
      - ./:/opt/go/src/github.com/russellwmy/goql-boilerplate
    environment:
      DEBUG: 'true'
      PORT: 3000
      REDIS_URI: localhost:6379
      REDIS_PASSOWRD: password
      # change 192.168.0.106 to your internal ip
      CONNECTION_STRING: root:123456@tcp(192.168.0.109:3306)/app?charset=utf8&parseTime=True
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
    # stdin_open: true
    # tty: true
    # command: bash
    command: go run /opt/go/src/github.com/russellwmy/goql-boilerplate/main.go
